name: solar_hunt
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.2+12

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.0
  image_picker: ^0.6.7+22
  image_fade: ^0.2.1
  animations: ^1.1.2
  flutter_map: ^0.10.1+1
  flutter_map_location_marker: ^0.0.6
  http: ^0.12.0+1
  progress_state_button: ^1.0.1
  location: ^3.0.2
  path_provider: ^1.6.14
  sqflite: ^1.3.1+1
  step_progress_indicator: ^0.2.4+7
  shared_preferences: ^0.5.10
  url_launcher: ^6.0.3
  flutter_exif_plugin:
    git:
      url:
        https://github.com/mukhikaran/flutter_exif.git
  intl: ^0.16.0
  oauth2_client: ^1.6.1
  jwt_decoder: ^1.0.3
  flutter_markdown: ^0.5.2
  flutter_native_splash: ^0.3.2
  teledart: ^0.1.6


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  flutter_launcher_icons:  ^0.8.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/panel-icon.png"

flutter_native_splash:
  color: "#fef1e0"
  color_dark: "#150030"
  image: assets/branding/splash-icon.png


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/
     - assets/badges/
     - assets/branding/
     - assets/backgrounds/
     - assets/icons/
     - assets/images/
     - assets/text/
