name: Build the Android App
on:
  workflow_dispatch:
    inputs:
      deleteme:
        description: "Foo"
        required: false
        default: "Bar"
jobs:
  build-release-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.8.1"
          channel: "stable"
          cache: true
          cache-key: flutter
      - run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" > android/app/key.asc
          gpg -d --passphrase "${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}" --batch android/app/key.asc > android/app/key.jks
      - run: |
          echo "${{ secrets.RELEASE_KEYPROPERTIES }}" > android/key.properties.asc
          gpg -d --passphrase "${{ secrets.RELEASE_KEYPROPERTIES_PASSPHRASE }}" --batch android/key.properties.asc > android/key.properties
      - run: flutter clean
      - run: flutter pub get
      - run: flutter pub run flutter_launcher_icons:main
      - run: flutter pub run flutter_native_splash:create
      # TODO: change build-name to release tag version
      - run: |
          flutter build appbundle \
          --release \
          --build-name=0.0.${{ github.run_number }} \
          --build-number=${{ github.run_number }} \
          --dart-define=MAPILLARY_BEARER_TOKEN=${{ secrets.MAPILLARY_BEARER_TOKEN }} \
          --dart-define=MAPILLARY_CLIENT_ID=${{ secrets.MAPILLARY_CLIENT_ID }} \
          --dart-define=TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} \
          --dart-define=TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}
      - run: echo "Built release appbundle 0.0.$GITHUB_RUN_NUMBER ($GITHUB_RUN_NUMBER)"
      - uses: actions/upload-artifact@v2
        with:
          name: app-release.aab
          path: build/app/outputs/bundle/release/app-release.aab
